name: Unit tests
on:
  workflow_call:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          ecr: "false"
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set env variables
        run: |
          export BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)
          if [[ $BRANCH == "master" ]]; then
              echo "TAG=latest" >> "$GITHUB_ENV"
          else
              echo "TAG=test" >> "$GITHUB_ENV"
          fi

      - name: Unit tests
        run: |
          docker run nsavelyeva/snippman:${{env.TAG}} /snippman/tests/test_all.py
